spring:
  application:
    name: MTWGEasy

  datasource:
    url: jdbc:sqlite:src/main/resources/db/db.sqlite
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    properties:
      hibernate.format_sql: true
    properties.hibernate.entityManagerFactoryInterface: jakarta.persistence.EntityManagerFactory
